baseURL = 'https://asakew.github.io/hugo-blog/'
languageCode = 'en-us'
title = 'cyber-blog.github.io'
theme = 'dream'

[params]
    subtitle = 'The Best Widgets on Earth'
[params.contact]
    email = 'info@example.org'
    phone = '+1 202-555-1212'