baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'ABC Widgets, Inc.'
theme = 'ananke'

[services]
    [services.googleAnalytics]
        ID = 'G-PLG5CXS42K'

[params]
    subtitle = 'The Best Widgets on Earth'
[params.contact]
    email = 'info@example.org'
    phone = '+1 202-555-1212'